name: cricbuzz_clone
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cb_ui:
    path: ./packages/cb_ui
  
  cupertino_icons: ^1.0.2
  go_router: ^10.1.0
  flutter_platform_widgets: ^3.3.5
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  json_serializable: ^6.1.1
  json_annotation: ^4.4.0
  dio: ^5.3.2
  cached_network_image: ^3.2.3
  visibility_detector: ^0.4.0+2
  scrollable_positioned_list: ^0.3.8
  intl: ^0.18.1
  flutter_widget_from_html: ^0.14.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.5

flutter:
  uses-material-design: true
